// examples/angular_sample_app/src/app/app.component.ts
/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import '@googlemaps/extended-component-library/place_building_blocks/place_directions_button.js';
import '@googlemaps/extended-component-library/api_loader.js';
import '@googlemaps/extended-component-library/split_layout.js';
import '@googlemaps/extended-component-library/overlay_layout.js';
import '@googlemaps/extended-component-library/icon_button.js';
import '@googlemaps/extended-component-library/place_building_blocks/place_directions_button.js';
import '@googlemaps/extended-component-library/place_building_blocks/place_data_provider.js';
import '@googlemaps/extended-component-library/place_picker.js';
import '@googlemaps/extended-component-library/place_overview.js';

import {Component, ElementRef, ViewChild} from '@angular/core';
import type {OverlayLayout} from '@googlemaps/extended-component-library/overlay_layout.js';
import type {PlacePicker} from '@googlemaps/extended-component-library/place_picker.js';

const DEFAULT_CENTER = {
  lat: 45,
  lng: -98
};
const DEFAULT_ZOOM = 4;
const DEFAULT_ZOOM_WITH_LOCATION = 16;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  readonly mapsApiKey = import.meta.env.NG_APP_MAPS_API_KEY;

  college?: google.maps.places.Place;

  @ViewChild('overlay') overlay!: ElementRef<OverlayLayout>;

  get mapCenter() {
    return this.college?.location ?? DEFAULT_CENTER;
  }

  get mapZoom() {
    return this.college ? DEFAULT_ZOOM_WITH_LOCATION : DEFAULT_ZOOM;
  }

  selectCollege(e: Event) {
    this.college = (e.target as PlacePicker)?.value ?? undefined;
  }

  showReviews() {
    this.overlay.nativeElement.showOverlay();
  }

  hideReviews() {
    this.overlay.nativeElement.hideOverlay();
  }
}

<!--
  Copyright 2023 Google LLC

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<gmpx-api-loader [key]="mapsApiKey"></gmpx-api-loader>

<gmpx-split-layout row-reverse row-layout-min-width="700">
  <gmpx-overlay-layout #overlay slot="fixed">
    <div slot="main" class="main-container">
      <gmpx-place-picker for-map="gmap" type="university"
                         placeholder="Enter a college in the US or Canada"
                         country="us ca" (gmpx-placechange)="selectCollege($event)">
      </gmpx-place-picker>
      <gmpx-place-overview size="large" [place]="college" google-logo-already-displayed>
        <gmpx-icon-button slot="action" variant="filled" (click)="showReviews()">
          See Reviews
        </gmpx-icon-button>
        <gmpx-place-directions-button slot="action" variant="filled">
          Directions
        </gmpx-place-directions-button>
      </gmpx-place-overview>
    </div>
    <div slot="overlay">
      <gmpx-icon-button autofocus (click)="hideReviews()"
                        class="close-button">
        Close
      </gmpx-icon-button>
      <gmpx-place-data-provider [place]="college">
        <gmpx-place-reviews></gmpx-place-reviews>
      </gmpx-place-data-provider>
    </div>
  </gmpx-overlay-layout>
  <gmp-map slot="main" id="gmap" map-id="DEMO_MAP_ID"
           [zoom]="mapZoom" [center]="mapCenter">
    <gmp-advanced-marker [position]="college?.location"></gmp-advanced-marker>
  </gmp-map>
</gmpx-split-layout>

// examples/react_sample_app/src/App.jsx
/**
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as GMPX from '@googlemaps/extended-component-library/react';
import React from 'react';

import './App.css';
import {CollegePicker} from './CollegePicker';

const API_KEY = process.env.REACT_APP_MAPS_API_KEY;
const DEFAULT_CENTER = '45,-98';
const DEFAULT_ZOOM = 4;
const DEFAULT_ZOOM_WITH_LOCATION = 16;

/**
 * Sample app that helps users locate a college on the map, with place info such
 * as ratings, photos, and reviews displayed on the side.
 */
export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {college: undefined};
    this.overlayLayoutRef = React.createRef();
  }

  render() {
    // Converts the location LatLng object to a string in "lat,lng" format.
    // Note that (as of React 18) Web Components in JSX accept data only as
    // string attributes and not as properties.
    const location = this.state.college?.location?.toString().slice(1, -1);

    return (
      <div className="App">
        <GMPX.APILoader apiKey={API_KEY} />
        <GMPX.SplitLayout rowReverse rowLayoutMinWidth="700">
          <GMPX.OverlayLayout ref={this.overlayLayoutRef} slot="fixed">
            <div className="MainContainer" slot="main">
              <CollegePicker
                className="CollegePicker"
                forMap="gmap"
                onCollegeChange={(college) => this.setState({college})}
              />
              <GMPX.PlaceOverview
                size="large"
                place={this.state.college}
                googleLogoAlreadyDisplayed
              >
                <GMPX.IconButton
                  slot="action"
                  variant="filled"
                  onClick={() => this.overlayLayoutRef.current?.showOverlay()}
                >
                  See Reviews
                </GMPX.IconButton>
                <GMPX.PlaceDirectionsButton slot="action" variant="filled">
                  Directions
                </GMPX.PlaceDirectionsButton>
              </GMPX.PlaceOverview>
            </div>
            <div slot="overlay">
              <GMPX.IconButton
                autofocus
                className="CloseButton"
                onClick={() => this.overlayLayoutRef.current?.hideOverlay()}
              >
                Close
              </GMPX.IconButton>
              <GMPX.PlaceDataProvider place={this.state.college}>
                <GMPX.PlaceReviews />
              </GMPX.PlaceDataProvider>
            </div>
          </GMPX.OverlayLayout>
          <gmp-map
            id="gmap"
            slot="main"
            map-id="DEMO_MAP_ID"
            center={location ?? DEFAULT_CENTER}
            zoom={location ? DEFAULT_ZOOM_WITH_LOCATION : DEFAULT_ZOOM}
          >
            {location && (
              <gmp-advanced-marker position={location}></gmp-advanced-marker>
            )}
          </gmp-map>
        </GMPX.SplitLayout>
      </div>
    );
  }
}
